#!/usr/bin/env python3

def list(movie_list):
    if len(movie_list) == 0:
        print("There are no movies in the list.\n")
        return
    else:
        i = 1
        for row in movie_list: #row[2] is the cost to buy the move, row[3] is the movie rating, row[4] is the description
            print(str(i) + ". " + row[0] + " (" + str(row[1]) + ")" + (" $" ) + row[2] + " Rated: " + str(row[3]) + "/5" + " " + row[4])
            i += 1
        print()

def add(movie_list):
    name = input("Name: ")
    year = input("Year: ")
    cost = input("Cost: ")
    try:
        rating = input("Rating: ")
        if rating > 0 and rating < 5:
            
    except:
        print("Please, enter a number from 0 to 5")
    descrip = input("Enter a movie description: ")
    movie = []
    movie.append(name)
    movie.append(year)
    movie.append(cost)
    movie.append(rating)
    movie.append(descrip)
    movie_list.append(movie)
    print(movie[0] + " was added.\n")   

def delete(movie_list):
    number = int(input("Number: "))
    if number < 1 or number > len(movie_list):
        print("Invalid movie number.\n")
    else:
        movie = movie_list.pop(number-1)
        print(movie[0] + " was deleted.\n")

def find(movie_list):
    movie_ratings = [] #create an empty list that we will print later with the movies with ratings better than or equal to what the user inputed
    user_input = float(input("Enter a rating for a movie (0 to 5) you would like to find or better: "))
    for movie in movie_list: #search through each movie
        try:
            if movie[3]>= user_input: #compare what is in the 3rd spot in the movie_list movies to the user_input
                movie_ratings.append(movie) #append the movie if the rating is high enough to the movie_rating list
        except:
            print("Please enter a number from 0 to 5.")
    print(movie_ratings)

def display_menu():
    print("COMMAND MENU")
    print("list - List all movies")
    print("add -  Add a movie")
    print("del -  Delete a movie")
    print("find - Find movies by rating")
    print("exit - Exit program")
    print()    

def main():
    movie_list = [["Monty Python and the Holy Grail", 1975, "19.99", 4.7, "This movie is funny!"],
                  ["On the Waterfront", 1954, "15.95", 4.2, "This movie is a romance"],
                  ["Cat on a Hot Tin Roof", 1958, "19.99", 4, "This movie is a drama."]]

    display_menu()
    
    while True:        
        command = input("Command: ")
        if command == "list":
            list(movie_list)
        elif command == "add":
            add(movie_list)
        elif command == "del":
            delete(movie_list)
        elif command == "find":
            find(movie_list)
        elif command == "exit":
            break
        else:
            print("Not a valid command. Please try again.\n")
    print("Bye!")

if __name__ == "__main__":
    main()
