#!/usr/bin/env python3

def main():
    #Welcome Message
    print("Welcome to the Population Program")
    print("===========================")


    #set variables
    #put a loop in here
    #try:
    organisms = int(input("Please enter the number of organisms: "))
    daily_increase = float(input("Please enter the daily increase: "))
    days = int(input("Please enter number of days to multiply: "))
    #except:
        #print("You must enter a numeric value")

    #Calculations and print the outputs
    print("DAY\t\t POPULATION")
    for i in range(days):
        print(i+1,"\t\t",organisms)
        increase = (organisms*daily_increase) + organisms
        organisms = round(increase,6)
        



"""
Set organisms to user input int
Set daily increase to a user input float
Set days to user input int

"""


if __name__ == "__main__":
    main()
