#!/usr/bin/env python3
#Author: Avery Cordle
import csv

#File to get the tv shows
FILENAME = "tv_shows.csv"
#File to write to the tv shows
FILENAME2 = "shows_new.csv"

#call functions
def main():
    shows = read_shows()
    display_shows(shows)
    write_shows(shows)
    print("Bye!")

def read_shows():
    #create a list for the tv shows in the file
    shows = []
    #open and read the csv file
    with open(FILENAME, newline="") as  file:
        reader = csv.reader(file)
        for row in reader:
            shows.append(row)
    return shows

def display_shows(shows):
    for i in range(len(shows)):
        show = shows[i]
        #print off the comma deliminated values in their row
        print(show[0], " ",show[1], " ",show[2], " Genre: ",show[3], " Rating: ",show[4], " ",show[5])
    print()

def write_shows(shows):
    #write the shows list into another .csv file so that we can see it being written
    with open(FILENAME2, "w", newline="") as file:
        writer = csv.writer(file)
        writer.writerows(shows)

if __name__ == "__main__":
    main()
