#!/usr/bin/env python3
"""Author: Avery Cordle
Description: Calculate the future value for an investment
"""


def calculate_future_value(monthly_investment, yearly_interest, years):
    #converts the yearly values into monthly values
    monthly_interest_rate = yearly_interest/12/100
    months = years*12

    #calculate the future value
    future_value = 0.0 #to force a float use 0.0, not 0 for int
    for i in range(0, months): #0-23 if you enter 2 years
        future_value += monthly_investment
        monthly_interest = future_value * monthly_interest_rate
        future_value += monthly_interest
    return future_value #this gives future_value to the calling function

def main():
    choice = "y"
    while choice.lower() == "y":
        monthly_investment = float(input("Enter Monthly Investment:\t"))
        yearly_interest_rate = float(input("Enter Yearly Interest Rate:\t"))
        years = int(input("Enter Number of Years:\t\t"))

        #get and display te future value
        future_value = calculate_future_value(monthly_investment, yearly_interest_rate, years)
        print("Future value:\t\t\t" + str(round(future_value,2)))
        print()

        #see if they want to continue
        choice = input("Continue? (y/n): ")
        print()
    print("Bye")


if __name__== "__main__":
    main()
